mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=piwik
    - MYSQL_USER=piwik
    - MYSQL_PASSWORD=password

piwik:
  image: benhutchins/piwik
  links:
    - mysql
  ports:
    - 80:80
  volumes:
    - ./config:/var/www/html/config:rw
